pipeline:
  name: Build Java with Maven
  identifier: Build_Verademo_Harness_1695058116093
  projectIdentifier: Verademo_Harness
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1693612209080
        repoName: vguglielmoveracode/Verademo_Harness
        build: <+input>
  stages:
    - stage:
        name: Build Java App with Maven
        identifier: Build_Java_App_with_Maven
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build Java App
                  identifier: Build_Java_App
                  spec:
                    shell: Sh
                    command: mvn -B package --file pom.xml
              - parallel:
                  - step:
                      type: Run
                      name: Veracode Static Policy Scan
                      identifier: Veracode_Scanner
                      spec:
                        connectorRef: dockerhubkey
                        image: veracode/api-wrapper-java
                        shell: Sh
                        command: java -jar /opt/veracode/api-wrapper.jar -vid <+secrets.getValue("VERACODE_ID")> -vkey <+secrets.getValue("VERACODE_KEY")> -action UploadAndScan -createprofile true -appname "VeraDemo" -version Harness-<+codebase.prNumber>"_"<+pipeline.sequenceId> -sandboxname "Harness-VeraDemo" -createsandbox true -filepath target/verademo.war
                  - step:
                      type: Run
                      name: Veracode Static Pipeline Scan
                      identifier: Veracode_Static_Pipeline_Scan
                      spec:
                        connectorRef: dockerhubkey
                        image: veracode/pipeline-scan:latest
                        shell: Sh
                        command: java -jar /opt/veracode/pipeline-scan.jar -vid <+secrets.getValue("VERACODE_ID")> -vkey <+secrets.getValue("VERACODE_KEY")> --file target/verademo.war
                  - step:
                      type: Run
                      name: Veracode Software Composition Analysis
                      identifier: Veracode_Software_Composition_Analysis
                      spec:
                        shell: Bash
                        command: curl -sSL https://download.sourceclear.com/ci.sh | sh
                        envVariables:
                          SRCCLR_API_TOKEN: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mzk0NzMxLCJleHAiOjE2OTY4NzQ3ODIsImF1dGhvcml0aWVzIjoiQUdFTlQiLCJqdGkiOiJhNzQ5MzkzNi1hYzI0LTRlMjAtYmY2OS04MmVjMTZhOWVhYTMiLCJjbGllbnRfaWQiOiIiLCJzY29wZSI6W119.mRxOne5i0J0l78OqlQycf5AznUgSCqUHZ2HBKegWdF7nr9s99RzyCXq2boBWF7VSh86BMBYD5UCLFiTE_Bidbr-MzYMtgFL4_X_xket1g58R8o4AU4VxYYDjmqSz5CTBQWqxexRu6M71eSh0T1do5xzJoWofu5ogDNOeNQ-rIo0
