pipeline:
  name: Build Java with Maven
  identifier: Build_Java_with_Maven_1678720601015
  projectIdentifier: default_project
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1690836035770
        repoName: jmazoveracode/verademo
        build: <+input>
  stages:
    - stage:
        name: Build Java App with Maven
        identifier: Build_Java_App_with_Maven
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build Java App
                  identifier: Build_Java_App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      mvn -B package --file pom.xml
              - step:
                  type: Run
                  name: Veracode Scanner
                  identifier: Veracode_Scanner
                  spec:
                    shell: Sh
                    command: |-
                      curl -O https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/23.3.11.1/vosp-api-wrappers-java-23.3.11.1-dist.zip
                      unzip vosp-api-wrappers-java-23.3.11.1-dist.zip
                      ls -l
                      ls -l app
                      ls -l app/target
                      pwd
                      java -jar VeracodeJavaAPI.jar -vid <+secrets.getValue("VERACODE_ID")> -vkey <+secrets.getValue("VERACODE_KEY")> -action UploadAndScan -createprofile true -appname "Verademo" -version <+codebase.prNumber>"_"<+pipeline.sequenceId> -sandboxname "Harness" -createsandbox true  -scantimeout 30 -filepath ./app/target/verademo.war
