## This string will prefix the resources and pipeline.
## It will allow you to add a pipeline source from this
## template multiple times with unique names.
namePrefix: mvn_template

## The name of your Artifactory integration
artIntegration: myArtIntegration

##### Artifactory Build Info
## set this to `true` to publish a build
publishBuild: true
## set this to `true` to scan the published build
#scanBuild: true
## When publishBuild is enabled, a FileSpec resource will be created
## that points to the published build. Here you can specify a pattern
## to further narrow down the Artifacts that are referenced by the spec.
#buildSpecPattern: "*"

##### Repository Details
repo:
  path: jmazoveracode/verademo
  gitIntegration: GH
  branchPattern: "jfrog"

##### Maven configuration
mavenConfig:
  ## Here you specify the command to execute

  command: mvn -B package --file pom.xml
  #sourceLocation: "./src"
  ## These repos must first be created in Artifactory.
  ## resolver is used to resolve dependencies. It is recommended to
  ## use a remote repository so that any external dependencies will be cached
  ## in your local Artifactory instance. Deployer is where your Artifacts
  ## will be uploaded.
  resolverSnapshotRepo: templates-snapshot-remote
  resolverReleaseRepo: templates-release-remote
  deployerSnapshotRepo: templates-snapshot-local
  deployerReleaseRepo: templates-release-local
